### ISSUE TITLE
statcounter reference is incorrect

### ISSUE THREAD

**Issue by harishankarv** [madhurnitc/madhurnitc.github.io#1]
This [here](https://github.com/madhurnitc/madhurnitc.github.io/blob/master/index.html#L150) references the wrong statcounter, (which is mine @harishankarv's). This probably happened because you have cloned my repo directly and did not change that part of the code.  Due to this my statcounter incorreclty shows hits it is not supposed to have.  Please remove the reference to my statcounter or change to one of your own.

**Comment by srajappa** [comment]
This issue is still OPEN! that's sad

**Comment by madhurnitc** [comment]
didn't see the mail from the github, it got lost in updates tab.
